Iron out bugs in zsh version
This could use a lot of cleaning up
but I think I've worked out all the bugs.

diff --git a/wordstar b/wordstar
--- a/wordstar
+++ b/wordstar
@@ -1,17 +1,18 @@
 #!/bin/zsh -f
-# wordstar, version 0.5
+# wordstar, version 0.5.1
 # copyright 2024 Erik Ben Heckman <erik@heckman.ca>
 # shared under the terms of the MIT license
 
 # wordstar: Launch WordStar in an emulated DOS environment on MacOS
 
-if [[ $1 = --debug ]]; then set -x; shift; fi
+# if [[ $1 = --debug ]]; then set -x; shift; fi
 set -euo pipefail
+trap exit ZERR
 
 # default options
 # all but `dosbox_path` can be modified with command-line options
 # don't use '~' in paths as it wont be expanded
-typeset -A WS_SETTINGS=(
+typeset -A SETTINGS=(
 	[dosbox_path]="/Applications/dosbox-x.app/Contents/MacOS/dosbox-x"
 	[dosbox_config_path]="$HOME/Applications/WordStar/dosbox-x.conf"
 	[c_mount_path]="$HOME/Applications/WordStar/DOS root"
@@ -20,10 +21,17 @@ typeset -A WS_SETTINGS=(
 	[create_missing_paths]=false
 	[shell_only]=false
 	[documents_mount_path]=''
-	[documents_drive_letter]='D:'
+	[mount_drive]='D:'
+	[dosbox_output]=/dev/null
+	[verbose]=false
+	[help_level]=4
 )
 
-typeset -a WS_DOSBOX_ARGS=(
+typeset -A OPTIONS
+# what's left after the options are removed
+typeset -a ARGUMENTS
+
+typeset -a DOSBOX_ARGS=(
 	-fastlaunch
 	-noautoexec
 	-set 'sdl fullscreen=false'
@@ -34,13 +42,11 @@ typeset -a WS_DOSBOX_ARGS=(
 	-set 'ttf ptsize=30'
 	-set 'ttf lins=30'
 	-set 'ttf cols=96'
-	-c "@echo off"
 )
 
-typeset -a WS_WORDSTAR_ARGS
+typeset -a WORDSTAR_ARGS
 
-
-print_help(){
+help(){
 	echo "USAGE: wordstar [OPTIONS] [--] [DOCUMENT]
 
     Launches WordStar in an emulated DOS environment
@@ -60,7 +66,7 @@ print_help(){
                            customizations. Default help level is 2.
             For descriptions of the presets, see the following
             file in Robert J. Sawyer's WordStar archive:
-            '${WS_SETTINGS[c_mount_path]%/}/WS/VERSIONS.TXT'
+            '${SETTINGS[c_mount_path]%/}/WS/VERSIONS.TXT'
 
     -H <HELP-LEVEL>, --helplevel <HELP-LEVEL>
             Start WordStar with onethe specified help level:
@@ -74,7 +80,7 @@ print_help(){
             Run WordStar in fullscreen mode.
 
     -w, --window,
-            Run WordStar in a window. (Not fullscreen. Default.)
+            Run WordStar in a window, i.e. not fullscreen. (Default.)
 
     -p, --paths
             When creating a new document, create intermediate
@@ -90,11 +96,12 @@ print_help(){
             will be mounted, unless DOCUMENT is itself a directory,
             in which case it itself will be mounted.
 
-    -c <CONFIG_FILE>, --conf <CONFIG_FILE>, --config <CONFIG_FILE>
+    -c <PATH>, --conf <PATH>, --config <PATH>
             Specify a DOSBox-X config file file to use.
 
-    -x <CONFIG_FILE>, --dosbox, <CONFIG_FILE>, --dosbox-x <CONFIG_FILE>
-            Specify DOSBox-x program to use.
+    -x <PATH>, --dosbox <PATH>, --dosbox-x <PATH>
+            Specify location DOSBox-x program to use.
+            Default: '${SETTINGS[dosbox_path]}'.
 
     -d, --dos, --shell
             Don't launch WordStar, just launch DOSBox-X.
@@ -117,54 +124,110 @@ print_help(){
     WordStar archive, see https://sfwriter.com/ws7.htm
 
     The archive is stored locally as:
-        '${WS_SETTINGS[c_mount_path]%/}/WS/'.
+        '${SETTINGS[c_mount_path]%/}/WS/'.
 
     Its README file can be found here:
-        '${WS_SETTINGS[c_mount_path]%/}/WS/-README.TXT'.
+        '${SETTINGS[c_mount_path]%/}/WS/-README.TXT'.
 
 
 "
 }
 
+
+main(){
+	local mount_path wordstar_doc
+
+	set_SETTINGS_and_ARGUMENTS "$@"
+	# printf "%s\n" "${ARGUMENTS[@]}"
+
+	mount_path="$(get_mount_path "${ARGUMENTS[1]:-.}")"
+	# printf "mount_path='%s'\n" "$mount_path" >&2
+	wordstar_doc="$(get_wordstar_document "$mount_path" "${ARGUMENTS[1]:-.}")"
+	wordstar_doc="$(validate_8.3_path "$wordstar_doc")"
+
+
+	# printf "wordstar_doc='%s'\n" "$wordstar_doc" >&2
+
+	set_wordstar_arguments "$wordstar_doc"
+	set_dosbox_arguments "$mount_path"
+	launch_dosbox
+
+	# print_globals
+	# exit
+
+}
+set_wordstar_arguments(){ local wordstar_doc="$1"
+ 	WORDSTAR_ARGS+=( "/h${SETTINGS[help_level]}" "$wordstar_doc" )
+}
+
+launch_dosbox(){
+	if ${SETTINGS[verbose]}
+	then
+		"${SETTINGS[dosbox_path]}" "${DOSBOX_ARGS[@]}"
+	else
+		"${SETTINGS[dosbox_path]}" "${DOSBOX_ARGS[@]}" &> /dev/null
+	fi
+}
+
+set_dosbox_arguments(){ local mount_path="$1"
+	DOSBOX_ARGS+=(
+		-c "@mount -q ${SETTINGS[mount_drive]%:}: \"${mount_path}\""
+		-c "@${SETTINGS[mount_drive]%:}:"
+		-conf "${SETTINGS[dosbox_config_path]}"
+		-c "@mount -q C: \"${SETTINGS[c_mount_path]}\""
+	)
+
+	if $SETTINGS[fullscreen]
+	then
+		DOSBOX_ARGS+=(-fullscreen)
+	fi
+
+	if ${SETTINGS[shell_only]}
+	then
+		DOSBOX_ARGS+=(
+			-c "@mount D:"
+			-c "@echo WordStar arguments are: ${WORDSTAR_ARGS[*]}"
+		)
+	else
+		DOSBOX_ARGS+=(
+			-c "@${SETTINGS[wordstar_executable]} ${WORDSTAR_ARGS[*]}"
+			-c "@EXIT"
+		)
+	fi
+}
+
+
+
 function process_option(){ local key=$1 value=${2:-}
 	case $key in
-	help) help;;
-	version) version;;
-	config) WS_SETTINGS[dosbox_config_path]=$value;;
-	c-drive) WS_SETTINGS[c_mount_path]=$value;;
-	shell) WS_SETTINGS[shell_only]=true;;
-	verbose) WS_SETTINGS[verbose]=true;;
-	fullscreen) WS_SETTINGS[fullscreen]=true;;
-	window) WS_SETTINGS[fullscreen]=false;;
-	paths) WS_SETTINGS[create_missing_paths]=true ;;
-	mount) WS_SETTINGS[documents_mount_path]="${value%/}/";;
+	help) help; exit;;
+	version) version; exit;;
+	config) SETTINGS[dosbox_config_path]=$value;;
+	c-drive) SETTINGS[c_mount_path]=$value;;
+	shell) SETTINGS[shell_only]=true;;
+	verbose) SETTINGS[verbose]=true;;
+	fullscreen) SETTINGS[fullscreen]=true;;
+	window) SETTINGS[fullscreen]=false;;
+	paths) SETTINGS[create_missing_paths]=true ;;
+	mount) SETTINGS[documents_mount_path]="${value%/}/";;
 	preset) case $value in
-		pristine) WS_SETTINGS[wordstar_executable]=PRISTINE;;
-		subdues) WS_SETTINGS[wordstar_executable]=WSRJS;;
-		sawyer) WS_SETTINGS[wordstar_executable]=SAWYER;;
-		*) die "unknown preset: $value";;
+		pristine) SETTINGS[wordstar_executable]=PRISTINE;;
+		subdues) SETTINGS[wordstar_executable]=WSRJS;;
+		sawyer) SETTINGS[wordstar_executable]=SAWYER;;
+		*) die "invalid preset: $value";;
 		esac;;
 	helplevel) case $value in
-		<0-4>) WS_WORDSTAR_ARGS+=("/h$value");;
+		<0-4>) SETTINGS[help_level]=$value;;
 		*) die "invalid help level: $value";;
 		esac;;
-	dosbox-x) WS_SETTINGS[dosbox_path]=$value;;
-	*) die "unknown option: $key";;
+	dosbox-x) SETTINGS[dosbox_path]=$value;;
+	*) die "invalid option: $key";;
 	esac
 }
 
-parse_command_line_options(){
-	# TODO
-	# this section was in its own function, but `opts` was local,
-	# i'll try making it global and see if that works.
-	:
-}
-
-
-
-main(){
-
-	# TODO try again to move this to a function
+# parses command-line options and sets elements of global SETTINGS appropriately
+# leaves the remaining command-line arguments in global ARGUMENTS
+set_SETTINGS_and_ARGUMENTS(){
 	# zparseopts produces unsightly error messages
 	# e.g.:
 	#   main:zparseopts:3: bad option: -a
@@ -173,104 +236,98 @@ main(){
 	# this workaround uses a temporary file... it's the only way I could find
 	# that avoided running `zparseopts` in a subshell
 	local zparsopts_errors=$(mktemp)
-	local -A opts
 	trap "if [[ -f $zparsopts_errors ]]; then rm $zparsopts_errors; fi" EXIT
 
-	zparseopts -F -M -D -A opts $(print_help | help_opts) 2> $zparsopts_errors || :
+	# don't panic on error, we'll die later
+	zparseopts -F -M -D -A COMMAND_LINE_OPTIONS \
+		$(help | help_opts) 2> $zparsopts_errors || :
 
+	# die if errors were output
 	if [[ -s $zparsopts_errors ]]; then
 		die "$(cat $zparsopts_errors | sed 's/^[^ ]* //')"
 	fi
 
-	for k v in "${(@kv)opts}"
+	# process each option
+	for k v in "${(@kv)COMMAND_LINE_OPTIONS}"
 	do process_option ${k#--} $v
 	done
 
-	# TODO move this to a function
-	validate_executable ${WS_SETTINGS[dosbox_path]} "dosbox-x"
-	validate_file ${WS_SETTINGS[dosbox_config_path]} "config file"
-	WS_DOSBOX_ARGS+=( -conf "${WS_SETTINGS[dosbox_config_path]}" )
-	validate_dir ${WS_SETTINGS[c_mount_path]} "C: mount path"
-	WS_DOSBOX_ARGS+=( -c "mount -q C: \"${WS_SETTINGS[c_mount_path]}\"" )
-	if $WS_SETTINGS[fullscreen]; then WS_DOSBOX_ARGS+=(-fullscreen); fi
+	validate_settings
 
-	# WS_PARSE_OPT_ERRORS=$(cat /tmp/myfifo)
-	# rm /tmp/myfifo
-	# set | grep -E '^WS_[A-Z_]*='
-	# echo "args: $@"
+	# save the rest of the command-line arguments
+	ARGUMENTS=("$@")
+}
 
-	# TODO move this to a function
-	local mount_path
-	# TODO fix bug
-	# ${WS_SETTINGS[documents_mount_path]} always ends with a slash
-	mount_path=${WS_SETTINGS[documents_mount_path]:-${1:-.}}
-	mount_path=${${mount_path/*/${mount_path}_}:A:h}
 
-	# TODO move this to a function
-	# make sure mount_path exists
+get_mount_path(){ local target="${1:-.}"
+	dirname_unless_slash_terminated \
+		"${SETTINGS[documents_mount_path]:-"$target"}" |
+			validate_mount_path
+}
+dirname_unless_slash_terminated(){
+	print ${${1/*/${1}_}:A:h}
+}
+
+validate_mount_path(){ local mount_path="$(cat -)"
 	if [[ ! -d "$mount_path" ]]
 	then
-		if ${WS_SETTINGS[create_missing_paths]}
+		if ${SETTINGS[create_missing_paths]}
 		then
 			mkdir -p "$mount_path"
 		else
 			die "Directory '$mount_path' doesn't exist, use the -p option to create it."
 		fi
 	fi
-	WS_DOSBOX_ARGS+=(
-		-c "mount -q ${WS_SETTINGS[documents_drive_letter]%:}: \"${mount_path}\""
-		-c "${WS_SETTINGS[documents_drive_letter]%:}:"
-	)
-
-
-	# TODO move this to a function
-	local target_document wordstar_document
-	target_document=${${1:-.}:A}
-	wordstar_document="${(q)$(descendent ${target_document} ${mount_path} | reverse_slashes)}" ||
-		die "document '${target_document}' not accesible in mounted path '${mount_path}'"
-
-	# TODO fix bug
-	# the following execution from the command line at this path:
-	# /Users/erik/dev/_playground/zsh/globbing % wordstar dirln/foo/bar/
-	# results in:
-	# wordstar_document: \Users\erik\dev\_playground\zsh\globbing\dir\foo\bar
-	# mount_path: /Users/erik/dev/_playground/zsh/globbing/dir/foo/bar
-	# and in wordstar, it tries to open
-	# \\Users\\erik\\dev\\_playground\\zsh\\globbing\\dir\\foo\\bar
-
-
-print "wordstar_document: ${wordstar_document}"
-print "mount_path: ${mount_path}"
-exit
-
-	if ${WS_SETTINGS[shell_only]}
-	then
-		WS_DOSBOX_ARGS+=(
-			-c "mount D:"
-			-c "set WS_DOCUMENT=${wordstar_document}"
-			-c "echo WS_DOCUMENT is set to %WS_DOCUMENT%"
-		)
-	else
-		WS_DOSBOX_ARGS+=(
-			-c "$WS_SETTINGS[wordstar_executable] $WS_WORDSTAR_ARGS ${wordstar_document}"
-		)
-			# -c "EXIT"
-	fi
-
-# echo $WS_DOSBOX_ARGS; exit
-
-	"${WS_SETTINGS[dosbox_path]}" "${WS_DOSBOX_ARGS[@]}"
+	printf "%s" "$mount_path"
 }
+
+validate_8.3_path(){ local path="${1}"
+	for segment in ${(s:\:)path}
+	do
+		if [[ -n $segment ]] && ! is_valid_8.3_filename "$segment"
+		then
+			printf "%s" "$path"
+			die "path not in 8.3 format: $path"
+		fi
+	done
+	# printf "8.3 path: '%s'\n" "$path" >&2
+	printf "%s" "$path"
+}
+
+is_valid_8.3_filename(){ local filename="$1"
+	/usr/bin/grep -qE '^[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{1,8}(\.[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{0,3})?$' <<<"$filename"
+}
+
+validate_settings(){
+	validate_executable ${SETTINGS[dosbox_path]} "dosbox-x"
+	validate_file ${SETTINGS[dosbox_config_path]} "config file"
+	[[ -d ${SETTINGS[c_mount_path]} ]] ||
+		die "cant find C: mount path: '${SETTINGS[c_mount_path]}'"
+
+}
+
+get_wordstar_document(){ local mount_path="${1}" target_document="${2}"
+	target_document="$(
+		descendent "${target_document:A}" "${mount_path}" |
+			reverse_slashes
+	)" || die "document '${target_document}' not accesible in mounted path '${mount_path}'"
+	printf "%s" "$target_document"
+}
+
 
 
 # if target is in directory, or one of it's descendent directories
 # then print its relative path. Otherwise, print the target and return 1
 descendent(){ local target=$1 directory=$2
-	if [[ $target = $directory*  ]]
+	# printf "target=%s\n" "$target" >&2
+	# printf "directory=%s\n" "$directory" >&2
+	if [[ "${target}" = "${directory%/}"*  ]]
 	then
-		print "${target#$directory/}"
+		# printf "\ntarget=%s\n" "$target" >&2
+		# printf "directory=%s\n\n" "$directory" >&2
+		printf "%s" "${target#$directory}"
 	else
-		print $target
+		printf "%s" "$target"
 		return 1
 	fi
 }
@@ -278,67 +335,33 @@ descendent(){ local target=$1 directory=$2
 validate_executable(){ local file=$1 name=${2:-file}
 	[[ -x $file ]] || die "cant execute ${name}: '$file'"
 }
+
 validate_file() { local file=$1 name=${2:-file}
 	[[ -r $file ]] || die "cant read ${name}: '$file'"
 }
+
 validate_dir(){ local dir=$1 name=${2:-directory}
 	[[ -d $dir ]] || die "cant find ${name}: '$dir'"
-}
-strip_doc_dir(){ local path="$1"
-	echo "${path#"${DOCUMENT_ROOT_PATH%/}/"}"
-}
-
-prepend_doc_dir(){ local path; path="$(strip_doc_dir "$1")"
-	echo "${DOCUMENT_ROOT_PATH%/}/${path}"
 }
 
 reverse_slashes(){
 	sed 's|//*|\\|g'
 }
 
-find_ws_document(){ local path="$1"
-	for ws_doc_path in "$path" "$path".[Ww][Ss](N)
-	do
-		if [[ -e "$ws_doc_path" ]]; then
-			echo_info "$ws_doc_path" "ws_doc_path="
-			return
-		fi
-	done
-}
-
-foo(){
-	if [[ "$path" = */ ]]
-	then
-		$DOSBOX_MOUNT_MISSING_PATHS && /bin/mkdir -p $path
-		info "path="
-		ws_doc_path=""
-	else
-		$DOSBOX_MOUNT_MISSING_PATHS && /bin/mkdir -p $(/usr/bin/dirname $path)
-		ws_doc_path="${path%.[Ww][Ss]}.WS"
-	fi
-	echo_info "$ws_doc_path" "ws_doc_path="
-	# new document with WS extension
-}
-
-help(){
-	print_help
-	exit
-}
 version(){
 	/usr/bin/awk '/^#!/{next}/^#/{sub("^# *","");print;next}{exit}' "$ZSH_ARGZERO"
 }
 
-info(){
-	echo "$@" >&2
-}
-echo_info(){
-	echo "${@:1:1}"
-	info "${@:2}${@:1:1}"
-}
+# relies on `set -e` to exit on error
 die(){
-	echo "$1">&2
+	printf "%s\n" "$1">&2
 	exit 77
 }
+
+print_globals(){
+	set | grep -E '^(SETTINGS|COMMAND_LINE_OPTIONS|ARGS|DOSBOX_ARGS|WORDSTAR_ARGS)='
+}
+
 help_opts(){ /usr/bin/awk '
 # help_opts v1.0 2024-08-17
 
