define settings and cmd-line opts in help text

diff --git a/wordstar b/wordstar
--- a/wordstar
+++ b/wordstar
@@ -5,29 +5,25 @@
 
 
 # wordstar launcher: Launch WordStar in an emulated DOS environment on MacOS
-if [[ $1 = --trace ]]; then set -x; shift; fi
+
+
+# this version defines settings and command-line options in the help text
+
 setopt NO_UNSET PIPE_FAIL ERR_RETURN
 
-# default options
-# all but `dosbox_path` can be modified with command-line options
-# don't use '~' in paths as it wont be expanded
-
-# [dosbox_path]="/opt/homebrew/bin/dosbox-x"
-
+# APP_DATA is only used in the following initialization of SETTINGS
+readonly APP_DATA="$HOME/Applications/WordStar"
+# most default settings are defined in the help text,
+# and override any defined here
 typeset -A SETTINGS=(
+	[c_mount_path]="$APP_DATA/DOS root"
+	[dosbox_config_path]="$APP_DATA/DOS root/WS/DOSBox-X/dosbox-x.conf"
+	[dosbox_mapper_path]="$APP_DATA/mapper-dosbox-x.map"
+	# [dosbox_path]="/opt/homebrew/bin/dosbox-x"
 	[dosbox_path]="/Applications/dosbox-x.app/Contents/MacOS/dosbox-x"
-	[dosbox_config_path]="$HOME/Applications/WordStar/DOS root/WS/DOSBox-X/dosbox-x.conf"
-	[dosbox_mapper_path]="$HOME/Applications/WordStar/mapper-dosbox-x.map"
-	[c_mount_path]="$HOME/Applications/WordStar/DOS root"
-	[wordstar_executable]="WS"
-	[fullscreen]=false
-	[create_missing_paths]=false
-	[shell_only]=false
-	[documents_mount_path]=''
-	[mount_drive]='D:'
-	[verbose]=false
-	[help_level]=4
+	[mount_drive]=D: # anything but C: or Z: is ok.
 )
+
 
 typeset -a DOSBOX_ARGS=(
 	-fastlaunch
@@ -42,24 +38,37 @@ typeset -a DOSBOX_ARGS=(
 	-set 'ttf cols=96'
 )
 
-# error codes
 
+# error codes
 ERR_BAD_OPTIONS=69
-ERR_NO_DOSBOX=3
-ERR_NO_CONFIG=4
-ERR_NO_C_MOUNT=5
 ERR_NO_DOC_MOUNT=6
 ERR_NO_NEW_DOC_MOUNT=7
 ERR_NO_ACCESS=8
 ERR_BAD_TARGET=9
 ERR_BAD_DOS_NAME=10
-ERR_INVALID_PARAMETER=11
+ERR_BAD_SETTING=11
+ERR_NO_EXEC=12
+ERR_NO_DIR=13
+ERR_NO_READ=14
+ERR_INTERNAL=66
 
-typeset -a OPTIONS
+readonly -A ERROR_MESSAGES=(
+	[$ERR_BAD_SETTING]="invalid %s: %s"
+	[$ERR_BAD_TARGET]="target document '%s' exists and is not a file or directory."
+	[$ERR_BAD_DOS_NAME]="path to '%s' not in DOS 8.3 format"
+	[$ERR_NO_DOC_MOUNT]="'%s' is not a directory, use the -p option to create it."
+	[$ERR_NO_NEW_DOC_MOUNT]="can't create directory for document mount-point: %s"
+	[$ERR_NO_ACCESS]="document '%s' is not accessible from document mount point '%s'."
+	[$ERR_NO_EXEC]="can't execute %s file: %s"
+	[$ERR_NO_DIR]="can't find %s directory: %s"
+	[$ERR_NO_READ]="can't read %s file: %s"
+	[$ERR_INTERNAL]="internal error: %s"
+)
+
 typeset -a ARGUMENTS
 typeset -a WORDSTAR_ARGS
 
-help(){
+annotated_help(){
 	echo "USAGE: wordstar [OPTIONS] [--] [DOCUMENT]
 
     Launches WordStar in an emulated DOS environment provided by DOSBox-X
@@ -73,36 +82,33 @@ help(){
 
     OPTIONS:
 
-    -P <PRESET>, --preset <PRESET>
-            Start WordStar with one of the folloing presets:
-                pristine   an unmodified out-of-the-box WordStar
-                subdued    R.J. Sawyer's custom less-harsh colour scheme
-                sawyer     R.J. Sawyer's preferred layout and extensive
+    -P <PRESET>, --preset <PRESET> # wordstar_executable WS
+            Start WordStar with one of the following presets: # -c preset
+                pristine   an unmodified out-of-the-box WordStar # PRISTINE
+                subdued    R.J. Sawyer's custom less-harsh colour scheme # WSRJS
+                sawyer     R.J. Sawyer's preferred layout and extensive # SAWYER
                            customizations. Default help level is 2.
             For descriptions of the presets, see '/WS/VERSIONS.TXT'
             in Robert J. Sawyer's WordStar archive.
 
 
-    -H <HELP-LEVEL>, --helplevel <HELP-LEVEL>
-            Start WordStar with onethe specified help level:
-                0    About help leve 0
-                1    About help leve 1
-                2    About help leve 2
-                3    About help leve 3
-                4    About help leve 4 (default)
+    -H <HELP-LEVEL>, --helplevel <HELP-LEVEL> # help_level 4
+            Start WordStar with one the specified help levels: # -c help level
+                0    help-level 0 #
+                1    help-level 1 #
+                2    help-level 2 #
+                3    help-level 3 #
+                4    help-level 4 (default) #
 
-    -f, --fullscreen
-            Run WordStar in fullscreen mode.
+    -f, --fullscreen # fullscreen false
+            Toggle fullscreen mode. By default WordStar runs in a window.
 
-    -w, --window
-            Run WordStar in a window, i.e. not fullscreen. (Default.)
-
-    -p, --paths
+    -p, --paths # create_missing_paths
             When creating a new document, create intermediate
             directories as required.
 
-    -d <DOCUMENT-ROOT>, --documents <DOCUMENT-ROOT>
-            Mount the specified path as the document root.
+    -d <DOCUMENT-ROOT>, --documents <DOCUMENT-ROOT> # documents_mount_path
+            Mount the specified path as the document root. # -d "document root"
             Only files in this directory tree will be accessible by WordStar.
             With this option, if DOCUMENT is provided as a relative path,
             it will be relative to this path.
@@ -111,28 +117,30 @@ help(){
             will be mounted, unless DOCUMENT is itself a directory,
             in which case it itself will be mounted.
 
-    -c <PATH>, --conf <PATH>, --config <PATH>
-            Specify a DOSBox-X config file file to use.
+    -c <PATH>, --conf <PATH>, --config <PATH> # dosbox_config_path
+            Specify a DOSBox-X config file file to use. # -r "dosbox config"
 
-	-m <PATH>, --mapper
-            Specify a DOSBox-X key-mapper file file to use.
+	-m <PATH>, --mapper # dosbox_mapper_path
+            Specify a DOSBox-X key-mapper file file to use. # -r "dosbox mapper"
 
-    -x <PATH>, --dosbox <PATH>, --dosbox-x <PATH>
-            Specify location DOSBox-x program to use.
-            Default: '${SETTINGS[dosbox_path]}'.
+    -x <PATH>, --dosbox <PATH>, --dosbox-x <PATH> # dosbox_path
+            Specify location DOSBox-x program to use. # -x dosbox
 
-    -s, --dos, --shell
+    -s, --dos, --shell # shell_only
             Don't launch WordStar, just launch DOSBox-X.
 
-    -r <DOS-ROOT>, --root <DOS-ROOT>, --c-drive <DOS-ROOT>
-            Specify a path to mount as the DOS root directory (C: drive)
+    -r <DOS-ROOT>, --root <DOS-ROOT>, --c-drive <DOS-ROOT> # c_mount_path
+            Specify a path to mount as the DOS root directory (C: drive) # -d "dos root"
             This directory must contain the WS directory
             from Robert J. Sawyer's WordStar archive.
 
-    -h, --help
+    -v, --verbose # verbose
+            Print debugging information.
+
+    -h, --help # help()
             Print this helpful message and exit.
 
-    -V, --version
+    -V, --version # version()
             Print version and copyright message and exit.
 
 
@@ -141,15 +149,10 @@ help(){
     For more information about WordStar, and Robert J. Sawyer's
     WordStar archive, see https://sfwriter.com/ws7.htm
 
-    The archive is stored locally as:
-        '${SETTINGS[c_mount_path]%/}/WS/'.
-
-    Its README file can be found here:
-        '${SETTINGS[c_mount_path]%/}/WS/-README.TXT'.
-
-
 "
 }
+
+if [[ $1 == "debug" ]]; then help; exit; fi
 
 print_env(){
 	set | grep -E "^(${(j:|:)@})=" >&2
@@ -160,19 +163,29 @@ print_globals(){
 	# set | grep -E '^(SETTINGS|COMMAN_LINE_ARGUMENTS|DOSBOX_ARGS|WORDSTAR_ARGS)=' >&2
 }
 
-peek(){ printf "%s='%s'\n" $1 $2 >&2; }
+
+peek(){
+	# set | grep "^$1="
+}
+peek2(){
+	set | grep "^$1="
+}
+
 
 main(){
+
 	local argument target mount_path wordstar_document
 
-	set_OPTIONS_and_ARGUMENTS "$@"
-	set_SETTINGS
+	set_SETTINGS_and_ARGUMENTS "$@"
 
 	argument=${ARGUMENTS[1]:-.}
 
 	doc_mount=$(get_doc_mount "$argument") || invalid "$doc_mount" # uses SETTINGS
 	target=$(get_target $argument $doc_mount ) || invalid "$target" "$doc_mount"
 	ws_doc=$(get_ws_doc $doc_mount $target) || invalid "$ws_doc"
+
+	# peek2 doc_mount
+	# exit
 
 	set_WORDSTAR_ARGS "$ws_doc" # uses SETTINGS
 
@@ -183,30 +196,9 @@ main(){
 	launch_dosbox
 }
 
-set_OPTIONS_and_ARGUMENTS(){
-	zparseopts -F -M -D -A OPTIONS $(help | help_opts) \
-		2> >(sed -e 's/^[^ ]* //' >&2) || exit $ERR_BAD_OPTIONS
-	ARGUMENTS=("$@")
-}
-
-set_SETTINGS(){
-	for option value in "${(@kvv)OPTIONS}"
-	do process_option ${option#--} $value
-	done
-
-	# validation
-	check_path -x ${SETTINGS[dosbox_path]} $ERR_NO_DOSBOX
-	check_path -r ${SETTINGS[dosbox_config_path]} $ERR_NO_CONFIG
-	check_path -d ${SETTINGS[c_mount_path]} $ERR_NO_C_MOUNT
-}
-
-check_path(){ check=$1 target=$2 error=$3
-	[[ -z $target ]] || test $check $target || die_by $error "$target"
-}
-
 get_doc_mount(){ local arg=$1 doc_mount
 
-	if [[ -n ${SETTINGS[documents_mount_path]} ]]
+	if [[ -v SETTINGS[documents_mount_path] ]]
 	then
 		doc_mount=${SETTINGS[documents_mount_path]}
 
@@ -285,73 +277,28 @@ launch_dosbox(){
 	fi
 }
 
-
 invalid(){
-	die_by $? "$@"
+	error $? "$@"
 }
 
-die_by(){ local error_code=$1; shift #...error message arguments
-	case $error_code in
-	$ERR_NO_DOSBOX)
-		die "cant execute dosbox-x: '$1'";;
-	$ERR_NO_CONFIG)
-		die "cant read config file: '$1'.";;
-	$ERR_NO_C_MOUNT)
-		die "cant find C: mount path: '$1'.";;
-	$ERR_NO_DOC_MOUNT)
-		die "'$1' is not a directory, use the -p option to create it.";;
-	$ERR_NO_NEW_DOC_MOUNT)
-		die "cannot create directory '$1' for document mount-point.";;
-	$ERR_NO_ACCESS)
-		die "document '$1' not within mounted tree rooted at '$2'.";;
-	$ERR_BAD_TARGET)
-		die "target document '$1' exists and is not a file or directory.";;
-	$ERR_BAD_DOS_NAME)
-		die "path to '$1' not in DOS 8.3 format";;
-	$ERR_INVALID_PARAMETER)
-		die "invalid $1: '$2'";;
-	0)
-		echo 0
-		die "$@";;
-	*)
-		die "unknown error '$?' with arguments '$*' ";;
-	esac
-}
-
-function process_option(){ local key=$1 value=${2:-}
-	case $key in
-	help) help; exit;;
-	version) version; exit;;
-	config) SETTINGS[dosbox_config_path]=$value;;
-	mapper) SETTINGS[dosbox_mapper_path]=$value;;
-	c-drive) SETTINGS[c_mount_path]=$value;;
-	shell) SETTINGS[shell_only]=true;;
-	verbose) SETTINGS[verbose]=true;;
-	fullscreen) SETTINGS[fullscreen]=true;;
-	window) SETTINGS[fullscreen]=false;;
-	paths) SETTINGS[create_missing_paths]=true ;;
-	documents) SETTINGS[documents_mount_path]="$value";;
-	preset) case $value in
-		pristine) SETTINGS[wordstar_executable]=PRISTINE;;
-		subdues) SETTINGS[wordstar_executable]=WSRJS;;
-		sawyer) SETTINGS[wordstar_executable]=SAWYER;;
-		*) die_by ERR_INVALID_PARAMETER preset $value;;
-		esac;;
-	helplevel) case $value in
-		<0-4>) SETTINGS[help_level]=$value;;
-		*) die_by ERR_INVALID_PARAMETER help-level $value;;
-		esac;;
-	dosbox-x) SETTINGS[dosbox_path]=$value;;
-	*) die_by ERR_INVALID_PARAMETER option $key;;
-	esac
+error(){ local error_code=$1; shift #...error-message arguments
+	if [[ -v ERROR_MESSAGES[$error_code] ]]
+	then die "$(printf "$ERROR_MESSAGES[$error_code]" "$@")" $error_code
+	else die "unknown error '$error_code' with arguments: $*"
+	fi
 }
 
 is_valid_dos_name(){ local filename=$1
 	/usr/bin/grep -qE '^[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{1,8}(\.[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{0,3})?$' <<<"$filename"
 }
 
+help(){
+	annotated_help | sed -E 's/[ \t]*#.*$//'
+	exit
+}
 version(){
 	/usr/bin/awk '/^#!/{next}/^#/{sub("^# *","");print;next}{exit}' "$ZSH_ARGZERO"
+	exit
 }
 
 die(){ local message=$1 code=${2:-$?}
@@ -359,51 +306,160 @@ die(){ local message=$1 code=${2:-$?}
 	exit $code
 }
 
+set_SETTINGS_and_ARGUMENTS(){
+	local -a help_opts_out
+	local options_definition_string
+	local -A functions commandline_options option_map defaults settings validations validation_parameters
+
+	help_opts_out=( "${(@f)$(annotated_help | help_opts)}" )
+	# peek help_opts_out
+
+	options_definition_string=${help_opts_out[1]}
+
+	functions=( ${(Q)${(z)help_opts_out[2]}} )
+	option_map=( ${(Q)${(z)help_opts_out[3]}} )
+	defaults=( ${(Q)${(z)help_opts_out[4]}} )
+	validations=( ${(Q)${(z)help_opts_out[5]}} )
+	validation_parameters=( ${(Q)${(z)help_opts_out[6]}} )
+
+	peek options_definition_string
+	zparseopts -F -M -D -A commandline_options ${=options_definition_string} \
+		2> >(sed -e 's/^[^ ]* //' >&2) || exit $ERR_BAD_OPTIONS
+
+	peek commandline_options
+	peek option_map
+	ARGUMENTS=("$@")
+
+	settings=( ${(kv)defaults} )
+
+	# apply command-line options to settings
+	for option value in "${(@kv)commandline_options}"
+	do
+		peek option
+		peek value
+		peek functions
+		if [[ -v functions[$option] ]]
+		then
+			$functions[$option] $value
+		elif [[ -n $value ]]
+		then settings[${option_map[$option]}]=$value
+		else case ${settings[${option_map[$option]}]:-} in
+			true) settings[${option_map[$option]}]=false;;
+			false) settings[${option_map[$option]}]=true;;
+			*) settings[${option_map[$option]}]="";;
+			esac
+		fi
+	done
+
+	peek settings
+
+	# validate settings
+	local -a validation_types
+	local -A validation_choices
+	# peek validations
+	for setting value in "${(@kv)settings}"
+	do
+		if [[ -v validations[$setting] ]]
+		then
+			set -- ${=validations[$setting]}
+			# echo "${validations[$setting]}"
+			zparseopts -D -F -a validation_types d x r c
+			# peek validation_types
+			for type in "${validation_types[@]}"
+			do case $type in
+				-d) [[ -d $value ]] || error $ERR_NO_DIR "$*" $value;;
+				-x) [[ -x $value ]] || error $ERR_NO_EXEC "$*" $value;;
+				-r) [[ -r $value ]] || error $ERR_NO_READ "$*" $value;;
+				-c) validation_choices=( ${(Q)${(z)validation_parameters[$setting]}} )
+					# peek validation_choices
+					if [[ $value != ${defaults[$setting]} ]]
+					then
+						[[ -v validation_choices[$value] ]] ||
+							error $ERR_BAD_SETTING "$*" $value
+						settings[$setting]=${validation_choices[$value]}
+					fi
+					;;
+				*) error $ERR_INTERNAL "type=$type, value=$value, args=$*";;
+				esac
+			done
+		fi
+	done
+	peek settings
+	SETTINGS=( ${(kv)SETTINGS} ${(kv)settings} )
+}
+
 # generate zparseopt string from help string
 help_opts(){ /usr/bin/awk '
-# help_opts v1.0 2024-08-17
+#!/usr/bin/awk -f
 
-function initialize_option(){
-	OPTION_BUFFER=""
-	REQUIRED_ARGUMENT=0
-	OPTIONAL_ARGUMENT=0
+# help_opts v2.0 2024-09-05
+function rem( pos){
+	if (pos=index($0,"#")) return substr($0,pos+1)
 }
-function add_option(name,key,req_arg,opt_arg){
-	OPTIONS=OPTIONS" "name""(req_arg ? ":" : (opt_arg ? "::" : ""))(key?"="key:"")
+function is_arg(){
+	if (match($f, /^<.*>$/)) return ":"
+	if (match($f, /^\[<.*>\]$/)) return "::"
 }
-function end_of_option(a,key,o){
-	split(OPTION_BUFFER,a," ")
-	key=a[1]
-	delete a[1]
-	add_option(key,"",REQUIRED_ARGUMENT,OPTIONAL_ARGUMENT)
-	for (o in a) add_option(a[o],key,REQUIRED_ARGUMENT,OPTIONAL_ARGUMENT)
-	initialize_option()
+function print_array(array,quotes){
+	for (key in array)
+		printf("%s %s%s%s ",key,quotes,array[key],quotes)
+	printf "\n"
 }
+
 BEGIN{
 	FS="[\t, ]+"
-	initialize_option()
-	OPTIONS=""
 }
-/\s*[^-]/{
-	for ( f=1; f<=NF; f++)
-		if ($f=="")
-			continue
-		else if (match($f, /^--?[a-zA-Z0-9][a-zA-Z0-9_-]*$/))
-			OPTION_BUFFER=substr($f,2)" "OPTION_BUFFER
-		else if (match($f, /^<.*>$/))
-			REQUIRED_ARGUMENT=1
-		else if (match($f, /^\[<.*>\]$/))
-			OPTIONAL_ARGUMENT=1
-		else
-			end_of_option()
-}
+# { print "==" $0 "==" }
 {
-	if (OPTION_BUFFER) end_of_option()
+	N1=1; while(!$N1&&N1<=NF&&$N1!=0) N1++
 }
-END {
-	print OPTIONS
+/^[ \t]*--?[a-zA-Z0-9]/{
+  # print "<" $1 ">"
+	KEY=substr($N1,2)
+	ARGS=""
+	for ( f=N1; f<=NF; f++ ) if (ARGS=is_arg()) break
+	for ( f=N1; f<=NF; f++ )
+		if (match($f, /^--?[a-zA-Z0-9][a-zA-Z0-9_-]*$/))
+			OPTIONS=OPTIONS " " substr($f,2) ARGS "=" KEY
+	if (match(comments=rem(), /^ *!?[a-zA-Z0-9][a-zA-Z0-9_-]* */)) {
+		SETTING=substr(comments,1,RLENGTH)
+		default=substr(comments,1+RLENGTH)
+		if (default=="()")
+			FUNCTIONS["-" KEY] = SETTING
+		else {
+			SETTINGS["-" KEY] = SETTING
+			if (ARGS) {
+				if (default!="") DEFAULTS[SETTING]=default
+			} else {
+				DEFAULTS[SETTING] = (default!="")? default : "false"
+			}
+		}
+	}
+	next
+}
+/#/{
+	if (VALIDATIONS[SETTING]) {
+		if (match(comments=rem(),/^[ \t]*$/)) comments=$N1
+		VALID_PARAMS[SETTING]= VALID_PARAMS[SETTING] " " $N1 " " comments
+	} else {
+		VALIDATIONS[SETTING]=rem()
+	}
 }
 
+END {
+	# print("OPTIONS")
+	print(OPTIONS)
+	# print("FUNCTIONS")
+	print_array(FUNCTIONS)
+	# print("SETTINGS")
+	print_array(SETTINGS)
+	# print("DEFAULTS")
+	print_array(DEFAULTS)
+	# print("VALIDATIONS")
+	print_array(VALIDATIONS,"\"")
+	# print("VALID_PARAMS")
+	print_array(VALID_PARAMS,"\"")
+}
 '
 }
 main "$@"
