Rework error handling
Managed to eliminate temporary file
required to produce
custom error messages for zparseopts,
but did it in a contrived fashion.

diff --git a/wordstar b/wordstar
--- a/wordstar
+++ b/wordstar
@@ -5,11 +5,8 @@
 
 
 # wordstar launcher: Launch WordStar in an emulated DOS environment on MacOS
-
-
-if [[ $1 = --debug ]]; then set -x; shift; fi
-set -euo pipefail
-# trap exit ZERR
+if [[ $1 = --trace ]]; then set -x; shift; fi
+setopt NO_UNSET PIPE_FAIL ERR_RETURN
 
 # default options
 # all but `dosbox_path` can be modified with command-line options
@@ -45,6 +42,20 @@ typeset -a DOSBOX_ARGS=(
 	-set 'ttf cols=96'
 )
 
+# error codes
+
+ERR_BAD_OPTIONS=69
+ERR_NO_DOSBOX=3
+ERR_NO_CONFIG=4
+ERR_NO_C_MOUNT=5
+ERR_NO_DOC_MOUNT=6
+ERR_NO_NEW_DOC_MOUNT=7
+ERR_NO_ACCESS=8
+ERR_BAD_TARGET=9
+ERR_BAD_DOS_NAME=10
+ERR_INVALID_PARAMETER=11
+
+typeset -a OPTIONS
 typeset -a ARGUMENTS
 typeset -a WORDSTAR_ARGS
 
@@ -143,82 +154,127 @@ print_env(){
 }
 
 print_globals(){
-	print_env SETTINGS ARGUMENTS DOSBOX_ARGS WORDSTAR_ARGS
-	# set | grep -E '^(SETTINGS|ARGUMENTS|DOSBOX_ARGS|WORDSTAR_ARGS)=' >&2
+	print_env OPTIONS ARGUMENTS SETTINGS DOSBOX_ARGS WORDSTAR_ARGS
+	# set | grep -E '^(SETTINGS|COMMAN_LINE_ARGUMENTS|DOSBOX_ARGS|WORDSTAR_ARGS)=' >&2
 }
 
 peek(){ printf "%s='%s'\n" $1 $2 >&2; }
 
+error_no(){ local code=$1
+	[[ $# -lt 2 ]] || shift && print -r ${(pj:\0:)@}
+	return $code
+}
+
+error(){ local code=$?
+	[[ $# -lt 1 ]] || print -r ${(pj:\0:)@}
+	return $code
+}
+
 main(){
-	local target mount_path wordstar_document
 
-	set_SETTINGS_and_ARGUMENTS "$@"
-	validate_settings
+	local output_buffer
+	# only non-error output is ever printed is help and version information
 
-	target="${${ARGUMENTS[1]:-.}}"
-	mount_path="${$(resolve_mount_path "$target")}"
-	validate_mount_path $mount_path
-	validate_target $target $mount_path
+	# todo : try and rework this error reporting using redirection
+	# something like main > >(do stdout stuff) 2> >(do stderr stuff))
+	# or do that in the problem areas, like parsing options,
+	# that was what led us here afterall.
 
-	# WordStar program will open document at this DOS path
-	wordstar_document="${$(resolve_wordstar_document "$target" "$mount_path"):-\\}"
-	validate_wordstar_document $wordstar_document
+	# if anonymous function returns non-0, stdout will be
+	# interpreted as null-delimited error arguments
+	output_buffer="$((){
+		local argument target mount_path wordstar_document
 
-	# use the SETTINGS global variable to set DOSBOX_ARGS and WORDSTAR_ARGS
-	set_wordstar_arguments "$wordstar_document"
-	set_dosbox_arguments "$mount_path" # uses WORDSTAR_ARGS
+		set_OPTIONS_and_ARGUMENTS "$@"
+		set_SETTINGS
 
-	# print_globals; exit
+		argument=${ARGUMENTS[1]:-.}
 
-	launch_dosbox
+		doc_mount=$(get_doc_mount "$argument") || error "$doc_mount" # uses SETTINGS
+		target=$(get_target $argument $doc_mount ) || error "$target" "$doc_mount"
+		ws_doc=$(get_ws_doc $doc_mount $target) || error "$ws_doc"
+
+		set_WORDSTAR_ARGS "$ws_doc" # uses SETTINGS
+
+		set_DOSBOX_ARGS "$doc_mount" # uses WORDSTAR_ARGS and SETTINGS
+
+		# print_globals; exit
+
+		launch_dosbox
+	} "$@")" || die_by "${(0)output_buffer}"
+	print -r "${(N)${(0)output_buffer}}"
 }
 
-validate_settings(){
-	(){ [[ -x $1 ]] || die_by NO_DOSBOX $1;} ${SETTINGS[dosbox_path]}
-	(){ [[ -r $1 ]] || die_by NO_CONFIG $1;} ${SETTINGS[dosbox_config_path]}
-	(){ [[ -d $1 ]] || die_by NO_C_MOUNT $1;} ${SETTINGS[c_mount_path]}
+set_OPTIONS_and_ARGUMENTS(){
+	# todo
+	# inseatead of 2>&1, to 2> >(die ERR_BAD_OPTIONS "$(cat -)")
+
+	zparseopts -F -M -D -A OPTIONS $(help | help_opts) 2>&1 ||
+		return $ERR_BAD_OPTIONS
+	ARGUMENTS=("$@")
 }
 
-validate_mount_path(){ local dir=$1
-	[[ -d "$dir" ]] && return
-	${SETTINGS[create_missing_paths]} || die_by NO_DOC_MOUNT "$dir"
-	mkdir -p $dir > /dev/null || die_by NO_NEW_DOC_MOUNT $dir
+set_SETTINGS(){
+	for option value in "${(@kvv)OPTIONS}"
+	do process_option ${option#--} $value
+	done
+
+	# validation
+	check_path -x ${SETTINGS[dosbox_path]} $ERR_NO_DOSBOX
+	check_path -r ${SETTINGS[dosbox_config_path]} $ERR_NO_CONFIG
+	check_path -d ${SETTINGS[c_mount_path]} $ERR_NO_C_MOUNT
 }
 
-validate_target(){ local target=${1:A} directory=${2:A}
-	[[ $target = $directory*  ]] || die_by NO_ACCESS "$target" "$directory"
-	[[ -d $target || -f $target || ! -e $target ]] ||
-		die_by BAD_TARGET_TYPE "$target"
+check_path(){ check=$1 target=$2 error=$3
+	[[ -z $target ]] || test $check $target || error_no $error "$target"
 }
 
-validate_wordstar_document(){ local dos_path=$1
-	is_valid_8.3_path "$dos_path" || die_by BAD_DOS_NAME "$dos_path"
-}
 
-resolve_mount_path(){ local target=$1
-	if [[ -n ${SETTINGS[documents_mount_path]} ]]; then
-		printf "%s" ${SETTINGS[documents_mount_path]}
-	elif [[ -d $target ]]; then
-		printf "%s" ${target}
-	elif [[ -e $target ]]; then
-		printf "%s" ${target:h}
-	elif [[ "${target[-1]}" = "/" ]]; then
-		printf "%s" ${target}
+get_doc_mount(){ local arg=$1 doc_mount
+
+	if [[ -n ${SETTINGS[documents_mount_path]} ]]
+	then
+		doc_mount=${SETTINGS[documents_mount_path]}
+
+	elif [[ -d $1 ]] || [[ ! -e $1 && "${1[-1]}" = "/" ]]
+	then
+		doc_mount=${arg}
 	else
-		printf "%s" ${target:h}
+		doc_mount=${arg:h}
 	fi
+
+	printf %s "${doc_mount:A}"
+
+	# validation
+	[[ -d "$doc_mount" ]] && return
+	${SETTINGS[create_missing_paths]} || return $ERR_NO_DOC_MOUNT
+	mkdir -p $doc_mount > /dev/null || return $ERR_NO_NEW_DOC_MOUNT
 }
 
-resolve_wordstar_document(){ local target=${1:A} directory=${2:A}
-	reverse_forward_slashes <<<${target#$directory}
+
+get_target(){ local target=${1:A} directory=${2:A}
+	printf "%s" "$target"
+	[[ -d $target || -f $target || ! -e $target ]] || return $ERR_BAD_TARGET
+	[[ $target = $directory*  ]] || return $ERR_NO_ACCESS
 }
 
 
-set_wordstar_arguments(){ local wordstar_document="$1"
+get_ws_doc(){ local directory=$1 target=$2 segments segment
+	segments=${(s:/:)target#$directory}
+	printf '\\%s' "${segments[@]}"
+	# validation
+	for segment in $segments
+	do
+		is_valid_dos_name || return $BAD_DOS_NAME
+	done
+}
+
+
+set_WORDSTAR_ARGS(){ local wordstar_document="$1"
  	WORDSTAR_ARGS+=( "/h${SETTINGS[help_level]}" "$wordstar_document" )
 }
 
-set_dosbox_arguments(){ local mount_path="$1"
+set_DOSBOX_ARGS(){ local mount_path="$1"
 	DOSBOX_ARGS+=(
 		-conf "${SETTINGS[dosbox_config_path]}"
 		-set mapperfile="${SETTINGS[dosbox_mapper_path]}"
@@ -255,26 +311,32 @@ launch_dosbox(){
 	fi
 }
 
-
-die_by(){ cause=$1; shift
-	case $cause in
-	NO_DOSBOX) die "cant execute dosbox-x: '$1'." 3;;
-	NO_CONFIG) die "cant read config file: '$1'." 4;;
-	NO_C_MOUNT) die "cant find C: mount path: '$1'." 5;;
-	NO_DOC_MOUNT)
-		die "'$1' is not a directory, use the -p option to create it." 6;;
-	NO_NEW_DOC_MOUNT)
-		die "cannot create directory '$1' for document mount-point." 7;;
-	NO_ACCESS)
-		die "document '$1' not within mounted tree rooted at '$2'." 8;;
-	BAD_TARGET_TYPE)
-		die "target document '$1' exists and is not a file or directory." 9;;
-	BAD_DOS_NAME)
-		die "path to '$1' not in DOS 8.3 format" 10;;
-	INVALID_PARAMETER)
-		die "invalid $1: '$2'" 11;;
+die_by(){
+	case $? in
+	$ERR_BAD_OPTIONS)
+		die "${1#* }";;
+	$ERR_NO_DOSBOX)
+		die "cant execute dosbox-x: '$1'";;
+	$ERR_NO_CONFIG)
+		die "cant read config file: '$1'.";;
+	$ERR_NO_C_MOUNT)
+		die "cant find C: mount path: '$1'.";;
+	$ERR_NO_DOC_MOUNT)
+		die "'$1' is not a directory, use the -p option to create it.";;
+	$ERR_NO_NEW_DOC_MOUNT)
+		die "cannot create directory '$1' for document mount-point.";;
+	$ERR_NO_ACCESS)
+		die "document '$1' not within mounted tree rooted at '$2'.";;
+	$ERR_BAD_TARGET)
+		die "target document '$1' exists and is not a file or directory.";;
+	$ERR_BAD_DOS_NAME)
+		die "path to '$1' not in DOS 8.3 format";;
+	$ERR_INVALID_PARAMETER)
+		die "invalid $1: '$2'";;
+	0)
+		die "$@";;
 	*)
-		die "unknown error: '$cause'" 2;;
+		die "unknown error '$?' with arguments '$*' ";;
 	esac
 }
 
@@ -295,75 +357,28 @@ function process_option(){ local key=$1 value=${2:-}
 		pristine) SETTINGS[wordstar_executable]=PRISTINE;;
 		subdues) SETTINGS[wordstar_executable]=WSRJS;;
 		sawyer) SETTINGS[wordstar_executable]=SAWYER;;
-		*) die_by INVALID_PARAMETER preset $value;;
+		*) error_no ERR_INVALID_PARAMETER preset $value;;
 		esac;;
 	helplevel) case $value in
 		<0-4>) SETTINGS[help_level]=$value;;
-		*) die_by INVALID_PARAMETER help-level $value;;
+		*) error_no ERR_INVALID_PARAMETER help-level $value;;
 		esac;;
 	dosbox-x) SETTINGS[dosbox_path]=$value;;
-	*) die_by INVALID_PARAMETER option $key;;
+	*) error_no ERR_INVALID_PARAMETER option $key;;
 	esac
 }
 
-
-## the functions that follow could moved to external libraries
-
-
-# parses command-line options and sets elements of global SETTINGS appropriately
-# leaves the remaining command-line arguments in global ARGUMENTS
-set_SETTINGS_and_ARGUMENTS(){
-	# zparseopts produces unsightly error messages
-	# e.g.:
-	#   main:zparseopts:3: bad option: -a
-	#   main:zparseopts:3: missing argument for option: -H
-	#
-	# this workaround uses a temporary file... it's the only way I could find
-	# that avoided running `zparseopts` in a subshell
-	local command_line_options
-	zparseopts_errors=$(mktemp)  zparseopts_errors=$(mktemp)
-	trap "if [[ -f $zparseopts_errors ]]; then rm $zparseopts_errors; fi" EXIT
-
-	# don't panic on error, we'll die later
-	zparseopts -F -M -D -A command_line_options \
-		$(help | help_opts) 2> $zparseopts_errors || :
-
-	# die if errors were output
-	if [[ -s $zparseopts_errors ]]; then
-		die "$(cat $zparseopts_errors | sed 's/^[^ ]* //')"
-	fi
-
-	# process each option
-	for k v in "${(@kv)command_line_options}"
-	do process_option ${k#--} $v
-	done
-
-	# save the rest of the command-line arguments
-	ARGUMENTS=("$@")
-}
-
-is_valid_8.3_path(){ local path="${1}"
-	for segment in ${(s:\:)path}
-	do [[ -z $segment ]] ||
-		is_valid_8.3_path_segment "$segment" || return 1
-	done
-}
-
-is_valid_8.3_path_segment(){ local filename=$1
+is_valid_dos_name(){ local filename=$1
 	/usr/bin/grep -qE '^[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{1,8}(\.[A-Za-z0-9!#$%&'"'"'()@^_`{}~-]{0,3})?$' <<<"$filename"
-}
-
-reverse_forward_slashes(){
-	sed 's|//*|\\|g'
 }
 
 version(){
 	/usr/bin/awk '/^#!/{next}/^#/{sub("^# *","");print;next}{exit}' "$ZSH_ARGZERO"
 }
 
-die(){
-	printf "%s\n" "$1">&2
-	exit "${2:-1}"
+die(){ local message=$1 code=${2:-$?}
+	print -r $message >&2
+	exit $code
 }
 
 help_opts(){ /usr/bin/awk '
@@ -413,4 +428,5 @@ END {
 '
 }
 main "$@"
+
 
